
server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # nginx的1111端口，做集群
        server-addr: 10.99.100.39:1111
      #server-addr: localhost:8848  # 配置nacos的地址
management:
  endpoints:
    web:
      exposure:
        include: "*"